# Generated by Django 5.1.15 on 2026-04-25 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField()),
                ('bank_account_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='ledger.merchant')),
            ],
            options={
                'db_table': 'payout',
                'indexes': [models.Index(fields=['merchant', '-created_at'], name='payout_merchant_idx'), models.Index(fields=['status', 'last_attempt_at'], name='payout_stuck_sweep_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='payout_amount_positive'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'completed', 'failed'])), name='payout_status_valid'), models.CheckConstraint(condition=models.Q(('attempts__gte', 0)), name='payout_attempts_nonneg')],
            },
        ),
    ]
