# Generated by Django 5.1.15 on 2026-04-25 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idempotency', '0001_initial'),
        ('ledger', '0001_initial'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencykey',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='ledger.merchant'),
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_keys', to='payouts.payout'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['created_at'], name='idempotency_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(fields=('merchant', 'key'), name='idempotency_merchant_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['in_flight', 'completed'])), name='idempotency_state_valid'),
        ),
    ]
