# Generated by Django 5.1.15 on 2026-04-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idempotency', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
